wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.3
    cli_version: 0.17.0
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1716111339
    t:
      1:
      - 1
      - 9
      - 50
      - 55
      - 103
      2:
      - 1
      - 9
      - 50
      - 55
      - 103
      3:
      - 2
      - 7
      - 13
      - 23
      - 66
      4: 3.11.3
      5: 0.17.0
      8:
      - 5
      13: linux-x86_64
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: ext/val/loss
      5: 1
      6:
      - 1
    - 1: ext/val/acc
      5: 1
      6:
      - 1
    - 1: ext/val/acc5
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: ext/train/loss
      5: 1
      6:
      - 1
    - 1: ext/train/acc
      5: 1
      6:
      - 1
    - 1: ext/train/acc5
      5: 1
      6:
      - 1
model:
  desc: null
  value: null
cfg/gpus:
  desc: null
  value:
  - 0
cfg/valid_method:
  desc: null
  value: loo
cfg/iftest:
  desc: null
  value: false
cfg/n_subs:
  desc: null
  value: 15
cfg/lr:
  desc: null
  value: 0.0007
cfg/wd:
  desc: null
  value: 0.00015
cfg/loss_temp:
  desc: null
  value: 0.07
cfg/max_epochs:
  desc: null
  value: 100
cfg/min_epochs:
  desc: null
  value: 30
cfg/patience:
  desc: null
  value: 30
cfg/num_workers:
  desc: null
  value: 8
