wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.3
    cli_version: 0.16.6
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1715585195.0
    t:
      1:
      - 1
      - 9
      - 50
      - 55
      - 103
      2:
      - 1
      - 9
      - 50
      - 55
      - 103
      3:
      - 7
      - 13
      - 23
      4: 3.11.3
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
    m:
    - 1: trainer/global_step
      6:
      - 3
