_target_: model.models.Conv_att_transformer
n_timeFilters: 16
timeFilterLen: 30
n_msFilters: 4
msFilter_timeLen: 3
n_channs: ${data.n_channs}
dilation_array: [1,3,6,12]
avgPoolLen: 15
timeSmootherLen: 3
multiFact: 2
stratified: ['initial', 'middle1', 'middle2']
activ: 'softmax'
temp: 1.0
saveFea: False
has_att: True
extract_mode: ${ext_fea.mode}
attention_mode: 'channel'

