wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.3
    cli_version: 0.17.0
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1716014355
    t:
      1:
      - 1
      - 9
      - 50
      - 55
      - 103
      3:
      - 23
      4: 3.11.3
      5: 0.17.0
      8:
      - 6
      13: linux-x86_64
