wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.3
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.30.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1713599075.0
    t:
      1:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 50
      - 55
      - 71
      - 103
      2:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 50
      - 55
      - 71
      - 103
      3:
      - 2
      - 7
      - 13
      - 23
      4: 3.11.3
      5: 0.16.6
      6: 4.30.2
      8:
      - 5
      13: linux-x86_64
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: val/loss
      5: 1
      6:
      - 1
    - 1: val/acc
      5: 1
      6:
      - 1
    - 1: val/acc5
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: train/loss
      5: 1
      6:
      - 1
    - 1: train/acc
      5: 1
      6:
      - 1
    - 1: train/acc5
      5: 1
      6:
      - 1
model:
  desc: null
  value: null
cfg/valid_method:
  desc: null
  value: loo
cfg/train_vids:
  desc: null
  value:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
cfg/val_vids:
  desc: null
  value:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
cfg/n_subs:
  desc: null
  value: 16
cfg/lr:
  desc: null
  value: 0.0007
cfg/wd:
  desc: null
  value: 0.00015
cfg/loss_temp:
  desc: null
  value: 0.07
cfg/max_epochs:
  desc: null
  value: 3
cfg/min_epochs:
  desc: null
  value: 1
cfg/gpus:
  desc: null
  value:
  - 4
cfg/num_workers:
  desc: null
  value: 8
